INSERT INTO [dbo].[Album] ([Title], [ArtistId]) VALUES
    (N'For Those About To Rock We Salute You', 1),
    (N'Balls to the Wall', 2),
    (N'Restless and Wild', 2),
    (N'Let There Be Rock', 1),
    (N'Big Ones', 3),
    (N'Jagged Little Pill', 4),
    (N'Facelift', 5),
    (N'Warner 25 Anos', 6),
    (N'Plays Metallica By Four Cellos', 7),
    (N'Audioslave', 8),
    (N'Out Of Exile', 8),
    (N'BackBeat Soundtrack', 9),
    (N'The Best Of Billy Cobham', 10),
    (N'Alcohol Fueled Brewtality Live! [Disc 1]', 11),
    (N'Alcohol Fueled Brewtality Live! [Disc 2]', 11),
    (N'Black Sabbath', 12),
    (N'Black Sabbath Vol. 4 (Remaster)', 12),
    (N'Body Count', 13),
    (N'Chemical Wedding', 14),
    (N'The Best Of Buddy Guy - The Millenium Collection', 15),
    (N'Prenda Minha', 16),
    (N'Sozinho Remix Ao Vivo', 16),
    (N'Minha Historia', 17),
    (N'Afrociberdelia', 18),
    (N'Da Lama Ao Caos', 18),
    (N'Acústico MTV [Live]', 19),
    (N'Cidade Negra - Hits', 19),
    (N'Na Pista', 20),
    (N'Axé Bahia 2001', 21),
    (N'BBC Sessions [Disc 1] [Live]', 22),
    (N'Bongo Fury', 23),
    (N'Carnaval 2001', 21),
    (N'Chill: Brazil (Disc 1)', 24),
    (N'Chill: Brazil (Disc 2)', 6),
    (N'Garage Inc. (Disc 1)', 50),
    (N'Greatest Hits II', 51),
    (N'Greatest Kiss', 52),
    (N'Heart of the Night', 53),
    (N'International Superhits', 54),
    (N'Into The Light', 55),
    (N'Meus Momentos', 56),
    (N'Minha História', 57),
    (N'MK III The Final Concerts [Disc 1]', 58),
    (N'Physical Graffiti [Disc 1]', 22),
    (N'Sambas De Enredo 2001', 21),
    (N'Supernatural', 59),
    (N'The Best of Ed Motta', 37),
    (N'The Essential Miles Davis [Disc 1]', 68),
    (N'The Essential Miles Davis [Disc 2]', 68),
    (N'The Final Concerts (Disc 2)', 58),
    (N'Up An'' Atom', 69),
    (N'Vinícius De Moraes - Sem Limite', 70),
    (N'Vozes do MPB', 21),
    (N'Chronicle, Vol. 1', 76),
    (N'Chronicle, Vol. 2', 76),
    (N'Cássia Eller - Coleção Sem Limite [Disc 2]', 77),
    (N'Cássia Eller - Sem Limite [Disc 1]', 77),
    (N'Come Taste The Band', 58),
    (N'Deep Purple In Rock', 58),
    (N'Fireball', 58),
    (N'Knocking at Your Back Door: The Best Of Deep Purple in the 80''s', 58),
    (N'Machine Head', 58),
    (N'Purpendicular', 58),
    (N'Slaves And Masters', 58),
    (N'Stormbringer', 58),
    (N'The Battle Rages On', 58),
    (N'Vault: Def Leppard''s Greatest Hits', 78),
    (N'Outbreak', 79),
    (N'Djavan Ao Vivo - Vol. 02', 80),
    (N'Djavan Ao Vivo - Vol. 1', 80),
    (N'Elis Regina-Minha História', 41),
    (N'The Cream Of Clapton', 81),
    (N'Unplugged', 81),
    (N'Album Of The Year', 82),
    (N'Angel Dust', 82),
    (N'King For A Day Fool For A Lifetime', 82),
    (N'The Real Thing', 82),
    (N'Deixa Entrar', 83),
    (N'In Your Honor [Disc 1]', 84),
    (N'In Your Honor [Disc 2]', 84),
    (N'One By One', 84),
    (N'The Colour And The Shape', 84),
    (N'My Way: The Best Of Frank Sinatra [Disc 1]', 85),
    (N'Roda De Funk', 86),
    (N'As Canções de Eu Tu Eles', 27),
    (N'Quanta Gente Veio Ver (Live)', 27),
    (N'Quanta Gente Veio ver--Bônus De Carnaval', 27),
    (N'Faceless', 87),
    (N'American Idiot', 54),
    (N'Appetite for Destruction', 88),
    (N'Use Your Illusion I', 88),
    (N'Use Your Illusion II', 88),
    (N'Blue Moods', 89),
    (N'A Matter of Life and Death', 90),
    (N'A Real Dead One', 90),
    (N'A Real Live One', 90),
    (N'Brave New World', 90),
    (N'Dance Of Death', 90),
    (N'Fear Of The Dark', 90),
    (N'Iron Maiden', 90),
    (N'Killers', 90),
    (N'Live After Death', 90),
    (N'Live At Donington 1992 (Disc 1)', 90),
    (N'Live At Donington 1992 (Disc 2)', 90),
    (N'No Prayer For The Dying', 90),
    (N'Piece Of Mind', 90),
    (N'Powerslave', 90),
    (N'Rock In Rio [CD1]', 90),
    (N'Rock In Rio [CD2]', 90),
    (N'Seventh Son of a Seventh Son', 90),
    (N'Somewhere in Time', 90),
    (N'The Number of The Beast', 90),
    (N'The X Factor', 90),
    (N'Virtual XI', 90),
    (N'Sex Machine', 91),
    (N'Emergency On Planet Earth', 92),
    (N'Synkronized', 92),
    (N'The Return Of The Space Cowboy', 92),
    (N'Get Born', 93),
    (N'Are You Experienced?', 94),
    (N'Surfing with the Alien (Remastered)', 95),
    (N'Jorge Ben Jor 25 Anos', 46),
    (N'Jota Quest-1995', 96),
    (N'Cafezinho', 97),
    (N'Living After Midnight', 98),
    (N'Unplugged [Live]', 52),
    (N'BBC Sessions [Disc 2] [Live]', 22),
    (N'Coda', 22),
    (N'Houses Of The Holy', 22),
    (N'In Through The Out Door', 22),
    (N'IV', 22),
    (N'Led Zeppelin I', 22),
    (N'Led Zeppelin II', 22),
    (N'Led Zeppelin III', 22),
    (N'Physical Graffiti [Disc 2]', 22),
    (N'Presence', 22),
    (N'The Song Remains The Same (Disc 1)', 22),
    (N'The Song Remains The Same (Disc 2)', 22),
    (N'A TempestadeTempestade Ou O Livro Dos Dias', 99),
    (N'Mais Do Mesmo', 99),
    (N'Greatest Hits', 100),
    (N'Lulu Santos - RCA 100 Anos De Música - Álbum 01', 101),
    (N'Lulu Santos - RCA 100 Anos De Música - Álbum 02', 101),
    (N'Misplaced Childhood', 102),
    (N'Barulhinho Bom', 103),
    (N'Seek And Shall Find: More Of The Best (1963-1981)', 104),
    (N'The Best Of Men At Work', 105),
    (N'Black Album', 50),
    (N'Garage Inc. (Disc 2)', 50),
    (N'Kill ''Em All', 50),
    (N'Load', 50),
    (N'Master Of Puppets', 50),
    (N'ReLoad', 50),
    (N'Ride The Lightning', 50),
    (N'St. Anger', 50),
    (N'...And Justice For All', 50),
    (N'Miles Ahead', 68),
    (N'Milton Nascimento Ao Vivo', 42),
    (N'Minas', 42),
    (N'Ace Of Spades', 106),
    (N'Demorou...', 108),
    (N'Motley Crue Greatest Hits', 109),
    (N'From The Muddy Banks Of The Wishkah [Live]', 110),
    (N'Nevermind', 110),
    (N'Compositores', 111),
    (N'Olodum', 112),
    (N'Acústico MTV', 113),
    (N'Arquivo II', 113),
    (N'Arquivo Os Paralamas Do Sucesso', 113),
    (N'Bark at the Moon (Remastered)', 114),
    (N'Blizzard of Ozz', 114),
    (N'Diary of a Madman (Remastered)', 114),
    (N'No More Tears (Remastered)', 114),
    (N'Tribute', 114),
    (N'Walking Into Clarksdale', 115),
    (N'Original Soundtracks 1', 116),
    (N'The Beast Live', 117),
    (N'Live On Two Legs [Live]', 118),
    (N'Pearl Jam', 118),
    (N'Riot Act', 118),
    (N'Ten', 118),
    (N'Vs.', 118),
    (N'Dark Side Of The Moon', 120),
    (N'Os Cães Ladram Mas A Caravana Não Pára', 121),
    (N'Greatest Hits I', 51),
    (N'News Of The World', 51),
    (N'Out Of Time', 122),
    (N'Green', 124),
    (N'New Adventures In Hi-Fi', 124),
    (N'The Best Of R.E.M.: The IRS Years', 124),
    (N'Cesta Básica', 125),
    (N'Raul Seixas', 126),
    (N'Blood Sugar Sex Magik', 127),
    (N'By The Way', 127),
    (N'Californication', 127),
    (N'Retrospective I (1974-1980)', 128),
    (N'Santana - As Years Go By', 59),
    (N'Santana Live', 59),
    (N'Maquinarama', 130),
    (N'O Samba Poconé', 130),
    (N'Judas 0: B-Sides and Rarities', 131),
    (N'Rotten Apples: Greatest Hits', 131),
    (N'A-Sides', 132),
    (N'Morning Dance', 53),
    (N'In Step', 133),
    (N'Core', 134),
    (N'Mezmerize', 135),
    (N'[1997] Black Light Syndrome', 136),
    (N'Live [Disc 1]', 137),
    (N'Live [Disc 2]', 137),
    (N'The Singles', 138),
    (N'Beyond Good And Evil', 139),
    (N'Pure Cult: The Best Of The Cult (For Rockers, Ravers, Lovers & Sinners) [UK]', 139),
    (N'The Doors', 140),
    (N'The Police Greatest Hits', 141),
    (N'Hot Rocks, 1964-1971 (Disc 1)', 142),
    (N'No Security', 142),
    (N'Voodoo Lounge', 142),
    (N'Tangents', 143),
    (N'Transmission', 143),
    (N'My Generation - The Very Best Of The Who', 144),
    (N'Serie Sem Limite (Disc 1)', 145),
    (N'Serie Sem Limite (Disc 2)', 145),
    (N'Acústico', 146),
    (N'Volume Dois', 146),
    (N'Battlestar Galactica: The Story So Far', 147),
    (N'Battlestar Galactica, Season 3', 147),
    (N'Heroes, Season 1', 148),
    (N'Lost, Season 3', 149),
    (N'Lost, Season 1', 149),
    (N'Lost, Season 2', 149),
    (N'Achtung Baby', 150),
    (N'All That You Can''t Leave Behind', 150),
    (N'B-Sides 1980-1990', 150),
    (N'How To Dismantle An Atomic Bomb', 150),
    (N'Pop', 150),
    (N'Rattle And Hum', 150),
    (N'The Best Of 1980-1990', 150),
    (N'War', 150),
    (N'Zooropa', 150),
    (N'UB40 The Best Of - Volume Two [UK]', 151),
    (N'Diver Down', 152),
    (N'The Best Of Van Halen, Vol. I', 152),
    (N'Van Halen', 152),
    (N'Van Halen III', 152),
    (N'Contraband', 153),
    (N'Vinicius De Moraes', 72),
    (N'Ao Vivo [IMPORT]', 155),
    (N'The Office, Season 1', 156),
    (N'The Office, Season 2', 156),
    (N'The Office, Season 3', 156),
    (N'Un-Led-Ed', 157),
    (N'Battlestar Galactica (Classic), Season 1', 158),
    (N'Aquaman', 159),
    (N'Instant Karma: The Amnesty International Campaign to Save Darfur', 150),
    (N'Speak of the Devil', 114),
    (N'20th Century Masters - The Millennium Collection: The Best of Scorpions', 179),
    (N'House of Pain', 180),
    (N'Radio Brasil (O Som da Jovem Vanguarda) - Seleccao de Henrique Amaro', 36),
    (N'Cake: B-Sides and Rarities', 196),
    (N'LOST, Season 4', 149),
    (N'Quiet Songs', 197),
    (N'Muso Ko', 198),
    (N'Realize', 199),
    (N'Every Kind of Light', 200),
    (N'Duos II', 201),
    (N'Worlds', 202),
    (N'The Best of Beethoven', 203),
    (N'Temple of the Dog', 204),
    (N'Carry On', 205),
    (N'Revelations', 8),
    (N'Adorate Deum: Gregorian Chant from the Proper of the Mass', 206),
    (N'Allegri: Miserere', 207),
    (N'Pachelbel: Canon & Gigue', 208),
    (N'Vivaldi: The Four Seasons', 209),
    (N'Bach: Violin Concertos', 210),
    (N'Bach: Goldberg Variations', 211),
    (N'Bach: The Cello Suites', 212),
    (N'Handel: The Messiah (Highlights)', 213),
    (N'The World of Classical Favourites', 214),
    (N'Sir Neville Marriner: A Celebration', 215),
    (N'Mozart: Wind Concertos', 216),
    (N'Haydn: Symphonies 99 - 104', 217),
    (N'Beethoven: Symhonies Nos. 5 & 6', 218),
    (N'A Soprano Inspired', 219),
    (N'Great Opera Choruses', 220),
    (N'Wagner: Favourite Overtures', 221),
    (N'Fauré: Requiem, Ravel: Pavane & Others', 222),
    (N'Tchaikovsky: The Nutcracker', 223),
    (N'The Last Night of the Proms', 224),
    (N'Puccini: Madama Butterfly - Highlights', 225),
    (N'Holst: The Planets, Op. 32 & Vaughan Williams: Fantasies', 226),
    (N'Pavarotti''s Opera Made Easy', 227),
    (N'Great Performances - Barber''s Adagio and Other Romantic Favorites for Strings', 228),
    (N'Carmina Burana', 229),
    (N'A Copland Celebration, Vol. I', 230),
    (N'Bach: Toccata & Fugue in D Minor', 231),
    (N'Prokofiev: Symphony No.1', 232),
    (N'Scheherazade', 233),
    (N'Bach: The Brandenburg Concertos', 234),
    (N'Chopin: Piano Concertos Nos. 1 & 2', 235),
    (N'Mascagni: Cavalleria Rusticana', 236),
    (N'Sibelius: Finlandia', 237),
    (N'Beethoven Piano Sonatas: Moonlight & Pastorale', 238),
    (N'Great Recordings of the Century - Mahler: Das Lied von der Erde', 240),
    (N'Elgar: Cello Concerto & Vaughan Williams: Fantasias', 241),
    (N'Adams, John: The Chairman Dances', 242),
    (N'Tchaikovsky: 1812 Festival Overture, Op.49, Capriccio Italien & Beethoven: Wellington''s Victory', 243),
    (N'Palestrina: Missa Papae Marcelli & Allegri: Miserere', 244),
    (N'Prokofiev: Romeo & Juliet', 245),
    (N'Strauss: Waltzes', 226),
    (N'Berlioz: Symphonie Fantastique', 245),
    (N'Bizet: Carmen Highlights', 246),
    (N'English Renaissance', 247),
    (N'Handel: Music for the Royal Fireworks (Original Version 1749)', 208),
    (N'Grieg: Peer Gynt Suites & Sibelius: Pelléas et Mélisande', 248),
    (N'Mozart Gala: Famous Arias', 249),
    (N'SCRIABIN: Vers la flamme', 250),
    (N'Armada: Music from the Courts of England and Spain', 251),
    (N'Mozart: Symphonies Nos. 40 & 41', 248),
    (N'Back to Black', 252),
    (N'Frank', 252),
    (N'Carried to Dust (Bonus Track Version)', 253),
    (N'Beethoven: Symphony No. 6 ''Pastoral'' Etc.', 254),
    (N'Bartok: Violin & Viola Concertos', 255),
    (N'Mendelssohn: A Midsummer Night''s Dream', 256),
    (N'Bach: Orchestral Suites Nos. 1 - 4', 257),
    (N'Charpentier: Divertissements, Airs & Concerts', 258),
    (N'South American Getaway', 259),
    (N'Górecki: Symphony No. 3', 260),
    (N'Purcell: The Fairy Queen', 261),
    (N'The Ultimate Relexation Album', 262),
    (N'Purcell: Music for the Queen Mary', 263),
    (N'Weill: The Seven Deadly Sins', 264),
    (N'J.S. Bach: Chaconne, Suite in E Minor, Partita in E Major & Prelude, Fugue and Allegro', 265),
    (N'Prokofiev: Symphony No.5 & Stravinksy: Le Sacre Du Printemps', 248),
    (N'Szymanowski: Piano Works, Vol. 1', 266),
    (N'Nielsen: The Six Symphonies', 267),
    (N'Great Recordings of the Century: Paganini''s 24 Caprices', 268),
    (N'Liszt - 12 Études D''Execution Transcendante', 269),
    (N'Great Recordings of the Century - Shubert: Schwanengesang, 4 Lieder', 270),
    (N'Locatelli: Concertos for Violin, Strings and Continuo, Vol. 3', 271),
    (N'Respighi:Pines of Rome', 226),
    (N'Schubert: The Late String Quartets & String Quintet (3 CD''s)', 272),
    (N'Monteverdi: L''Orfeo', 273),
    (N'Mozart: Chamber Music', 274),
    (N'Koyaanisqatsi (Soundtrack from the Motion Picture)', 275);