INSERT INTO [dbo].[Genre] ([Name]) VALUES
    (N'Rock'),
    (N'Jazz'),
    (N'Metal'),
    (N'Alternative & Punk'),
    (N'Rock And Roll'),
    (N'Blues'),
    (N'Latin'),
    (N'Reggae'),
    (N'Pop'),
    (N'Soundtrack'),
    (N'Bossa Nova'),
    (N'Easy Listening'),
    (N'Heavy Metal'),
    (N'R&B/Soul'),
    (N'Electronica/Dance'),
    (N'World'),
    (N'Hip Hop/Rap'),
    (N'Science Fiction'),
    (N'TV Shows'),
    (N'Sci Fi & Fantasy'),
    (N'Drama'),
    (N'Comedy'),
    (N'Alternative'),
    (N'Classical'),
    (N'Opera');