INSERT INTO [dbo].[Playlist] ([Name]) VALUES
    (N'Music'),
    (N'Movies'),
    (N'TV Shows'),
    (N'Audiobooks'),
    (N'90’s Music'),
    (N'Audiobooks'),
    (N'Movies'),
    (N'Music'),
    (N'Music Videos'),
    (N'TV Shows'),
    (N'Brazilian Music'),
    (N'Classical'),
    (N'Classical 101 - Deep Cuts'),
    (N'Classical 101 - Next Steps'),
    (N'Classical 101 - The Basics'),
    (N'Grunge'),
    (N'Heavy Metal Classic'),
    (N'On-The-Go 1');
